### PR TITLE
Bump to 2.0.0

### PR DESCRIPTION
**Pull request by eugenes78**
### Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have updated the `CHANGELOG` including this PR (where applicable)
- [x] I have run tests and automatic checks locally
- [x] I have run `pitest` check locally and checked that the coverage increased (or didn't change) or decreased insignificantly
- [x] I have made corresponding changes to the documentation (where applicable)
- [x] I have grouped commits logically or I promise to squash my commits before merge

### CODE REVIEW

**Comment by DzmitryFomchyn** [comment]
@eugenes78 @mapbox-danny Please note that after the version is bumped to 2.0.0 (GA), breaking changes will be prohibited without a major version bump. As far as I'm aware, there is at least one breaking change that you may want to address before the GA release: the removal of routable points from the [suggestion](https://github.com/mapbox/mapbox-search-android/blob/2d2b5c6e4b78dd67602e2a9c9157b489c261b8a8/MapboxSearch/place-autocomplete/src/main/java/com/mapbox/search/autocomplete/PlaceAutocompleteSuggestion.kt#L35).

**Comment by DzmitryFomchyn** [comment]
Sorry, accidentally closed this PR.

**Comment by mikeringrose** [comment]
> @eugenes78 @mapbox-danny Please note that after the version is bumped to 2.0.0 (GA), breaking changes will be prohibited without a major version bump. As far as I'm aware, there is at least one breaking change that you may want to address before the GA release: the removal of routable points from the [suggestion](https://github.com/mapbox/mapbox-search-android/blob/2d2b5c6e4b78dd67602e2a9c9157b489c261b8a8/MapboxSearch/place-autocomplete/src/main/java/com/mapbox/search/autocomplete/PlaceAutocompleteSuggestion.kt#L35).

@DzmitryFomchyn any more details on this? why is it to be removed?

**Comment by DzmitryFomchyn** [comment]
It [was in the plans](https://mapbox.atlassian.net/browse/SSDK-664), but it seems the issue has been closed for some reason.

Anyway, just wanted to give everyone a heads-up to make sure we're all on the same page about the importance of having a stable API once SDK reaches GA state. I'm not entirely sure about the search SDK team's plans and priorities.

**Review by mapbox-danny — APPROVED** [review]
.

**Pull request closed without merging**
