### PR TITLE
Create codeql.yml

### PR DESCRIPTION
**Pull request by ThibaudLopez**
Enable CodeQL

### CODE REVIEW

**Review by DzmitryFomchyn — APPROVED** [review]

**Comment by ThibaudLopez** [comment]
@DzmitryFomchyn , do you know how to setup CodeQL for Java for this repo? It failed to auto scan.

**Comment by DzmitryFomchyn** [comment]
> @DzmitryFomchyn , do you know how to setup CodeQL for Java for this repo? It failed to auto scan.

@ThibaudLopez it seems that the error is `SDK Registry token is not specified.` which comes from [here](https://github.com/mapbox/mapbox-search-android/blob/main/MapboxSearch/build.gradle#L6). We need a few more tokens to build the SDK ([more information](https://docs.mapbox.com/android/search/guides/install/)).

**Comment by ThibaudLopez** [comment]
@DzmitryFomchyn , do you know how to do the setup?

**Comment by ThibaudLopez** [comment]
see https://github.com/mapbox/mapbox-navigation-android/pull/7048 for example of CodeQL setup for Kotlin

**Comment by eugenes78** [comment]
Seems to be way outdated

**Comment by ThibaudLopez** [comment]
re-opening... we still need code scanning for this repo

**Comment by eugenes78** [comment]
@ThibaudLopez It's broken in its current form. CI/CD didn't pass.

**Comment by ThibaudLopez** [comment]
@eugenes78 , correct, CodeQL is not yet setup to build the Java project of this repo as the CodeQL auto-build doesn't succeed. We need somebody that's familiar with how to build this repo to please setup the CodeQL YAML to do the same build.

**Comment by ThibaudLopez** [comment]
@eugenes78 ,

> Are you making progress on this one? It's open for more than a year already...

No, we've been needing help for a year, somebody familiar with how to build this repo, then put those instructions in the CodeQL YAML. If needed, we can close this PR and leave this repo without code scanning. We can try the other code scanning (we can follow-up internally.

**Pull request closed without merging**
